export const STATE_LOGIN = "STATE_LOGIN";
export const STATE_SNACKBAR = "STATE_SNACKBAR";
export const STATE_MODAL = STATE_MODAL;
export const STATE_MODAL_LOGIN = "STATE_MODAL_LOGIN";
export const STATE_NAME = "STATE_NAME";
export const STATE_SAKIT = "STATE_SAKIT";
export const STATE_MODAL_LOCATION = "STATE_MODAL_LOCATION";
export const STATE_SIMPAN_LOKASI = "STATE_SIMPAN_LOKASI";
